travis:
  secure:
    BINSTAR_TOKEN: bss/lW3X55dHnQWJ/Jlz2a0sdLlH9OCepqEgXlU/ioM1Y9ruK9tJ0DNJpchzUJ0RNjBGepWBHyvUQajha0Zs6nbHwnec8Bqs6SMJYB+cGXyfSXcKzONYrAiM6Dd6vTMUAPnNRlCNLpY5yRjASh+b459gUBvFW5qh1XZnkQDfpgEdzqbT3wDUFjXj/LREhR5lBB6kMl7/QWYxa+Kiftkzq8Q/oD8GyKk/tyTwAAWJ1bmKpHhMkxvYttesTuVv9vy5JWHARIT0nIHUF66bXkwqFUC/5OkTrjj+h/KVVgblwS4WYd0c+Nc5no5DHiJ08xf0EYWS+stR/HQ5jrtj63gvooKW/DT3u5InvyJR/ej5xeoV/q9/0PD2ppDvj2cjoGs56dsC/mVc+fz3c3J3WNpj7N6hBZh3l3RU3bOS0LQ6rMS6DBfO9/C4pWxkNl1nQLCF7viNxEFLJcF38iEC+UHQEKDe2mvqT6k5nnJJC1RORE+aum/Jbz3XOIdWtjiseJ2er5bS2toxQelT6siDiDJYJbr/PVJIKb4M6t/ntfcu2S4Ouoh1gnS93zx3fqK7b3xHPc3ac+r9UVzmdNbOqZwUXIuV8V1TLGt3Am22ryCMebojv6vNDpBN9C6i31oH3IHApgsYVQW3aOh4qKc1OOVUWUL+RxTT1QedGeVFXkwk4VY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
